export { default as FotoKK } from "@/components/icons/FotoKK.vue";
export { default as GrayEye } from "@/components/icons/GrayEye.vue";
export { default as RedEye } from "@/components/icons/redEye.vue";
export { default as ElectionBox } from "@/components/icons/ElectionBox.vue";
export { default as LogOut } from "@/components/icons/logout.vue";
export { default as AddImage } from "@/components/icons/AddImage.vue";
export { default as RemoveImage } from "@/components/icons/RemoveImage.vue";
export { default as WarningIcon } from "@/components/icons/WarningIcon.vue";
export { default as LoadingSucces } from "@/components/icons/LoadingSucces.vue";
